### ISSUE TITLE
MIT License

### ISSUE THREAD

**Issue by jamonholmgren** [clearsightstudio/phpGenesis#1]
The current license is super restrictive. We need to change to MIT.

**Comment by silasjmatson** [comment]
Just realized that We'll have to modify almost every file to change... :anguished:

**Comment by jamonholmgren** [comment]
We can remove the headers from each file. They're no longer necessary now that phpGenesis is in a proper repo.

**Comment by jamonholmgren** [comment]
@tsantef -- can you give us permission (as a co-copyright holder) to MIT this?

**Comment by jamonholmgren** [comment]
(Just a note: Tim gave me permission via IM.)

**Comment by jamonholmgren** [comment]
Closed via https://github.com/clearsightstudio/phpGenesis/commit/af8eac54014fb58e771311682b5078c9805c7cc0.
